### PR TITLE
Release v1.4.2

### PR DESCRIPTION
**Pull request by JuliaKukulies**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by JuliaKukulies** [comment]
@conda-forge-admin, please rerender

**Comment by w-k-jones** [comment]
I'm not sure what's going on with the hash mismatch, as I get the same code as you do. Will have a quick look into it

**Comment by w-k-jones** [comment]
Ok, I'm now getting the following for the hash code, which matches what conda expects:

`e029e4495fdaf67ee350a89dd256f483968251aee93cbc8b7dc9423d54cc40aa`

Not sure what was causing the problem before

**Comment by JuliaKukulies** [comment]
Thanks @w-k-jones! I updated the code. Strangely, two letters are missing when I use another text editor to paste the code, but seems to work now :)

**Review by w-k-jones — APPROVED** [review]
Looks good to release, let me know if I need to merge it, as I'm not sure that adding you as a code owner worked properly

**Comment by JuliaKukulies** [comment]
Yes, looks like you will need to merge

**Pull request merged**
